android.useAndroidX=true
android.adbExecutable=/mnt/d/Apps/Android/Sdk/platform-tools/adb.exe
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
ksp.useKSP2=false
RELEASE_STORE_FILE=release.jks
RELEASE_STORE_PASSWORD=notilog123
RELEASE_KEY_ALIAS=notilog
RELEASE_KEY_PASSWORD=notilog123